CREATE TYPE "role" AS ENUM (
  'admin',
  'manager',
  'cook',
  'bartender',
  'waiter'
);

CREATE TYPE "order_item_status" AS ENUM (
  'pending',
  'preparing',
  'ready',
  'served',
  'cancelled'
);

CREATE TYPE "chat_channel" AS ENUM (
  'general',
  'kitchen',
  'bar',
  'direct'
);

CREATE TYPE "payment_method" AS ENUM (
  'cash',
  'card'
);

CREATE TABLE "settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurant_name" varchar(100) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'BGN',
  "opening_time" time,
  "closing_time" time
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(30) UNIQUE NOT NULL,
  "password_hash" varchar(60) NOT NULL,
  "first_name" varchar(30),
  "last_name" varchar(30),
  "role" role NOT NULL
);

CREATE TABLE "tables" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(10) UNIQUE NOT NULL,
  "capacity" integer NOT NULL
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "opened_at" timestamp NOT NULL DEFAULT (now()),
  "closed_at" timestamp,
  "table_id" bigint NOT NULL,
  "waiter_id" bigint NOT NULL
);

CREATE TABLE "menu_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "description" varchar(150),
  "price" decimal(10,2) NOT NULL,
  "available" boolean NOT NULL DEFAULT true
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "menu_item_id" bigint NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "note" varchar(200),
  "status" order_item_status NOT NULL DEFAULT 'pending',
  "ordered_price" decimal(10,2) NOT NULL,
  "sent_at" timestamp,
  "ready_at" timestamp,
  "delivered_at" timestamp
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "menu_items_categories" (
  "menu_item_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  PRIMARY KEY ("menu_item_id", "category_id")
);

CREATE TABLE "receipts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint UNIQUE NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "tip" decimal(10,2) NOT NULL DEFAULT 0,
  "total" decimal(10,2) NOT NULL,
  "payment_method" payment_method NOT NULL,
  "issued_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "menu_item_reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rating" integer NOT NULL CHECK (rating >= 1 AND rating <= 10),
  "text" text,
  "menu_item_id" bigint NOT NULL
);

CREATE TABLE "user_ratings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rating" integer NOT NULL CHECK (rating >= 1 AND rating <= 10),
  "text" text,
  "user_id" bigint NOT NULL
);

CREATE TABLE "ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(80) NOT NULL,
  "unit" varchar(10) NOT NULL,
  "current_stock" decimal(10,3) NOT NULL DEFAULT 0,
  "min_stock" decimal(10,3) NOT NULL DEFAULT 0
);

CREATE TABLE "recipes" (
  "menu_item_id" bigint NOT NULL,
  "ingredient_id" bigint NOT NULL,
  "quantity" decimal(10,3) NOT NULL,
  PRIMARY KEY ("menu_item_id", "ingredient_id")
);

CREATE TABLE "chat_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channel" chat_channel NOT NULL,
  "content" varchar(1000) NOT NULL,
  "sent_at" timestamp NOT NULL DEFAULT (now()),
  "sender_id" bigint NOT NULL,
  "recipient_id" bigint CHECK ((channel = 'direct' AND recipient_id IS NOT NULL) OR (channel != 'direct' AND recipient_id IS NULL))
);

CREATE TABLE "menus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "description" varchar(200),
  "is_active" boolean NOT NULL DEFAULT false
);

CREATE TABLE "menus_menu_items" (
  "menu_id" bigint NOT NULL,
  "menu_item_id" bigint NOT NULL,
  PRIMARY KEY ("menu_id", "menu_item_id")
);

ALTER TABLE "orders" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("waiter_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_items_categories" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_items_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receipts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_item_reviews" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipes" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipes" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus_menu_items" ADD FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus_menu_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
